keys:
  - &home-desktop age1wz5pek04hmplxklvncq7xtzygjvdlrxrpknlcmmhrhc92hhdyp2qwyf4u7
  - &home-server-1 age1nsmpn9ar69nkeyjwdvz7mrgd8fygt2vsz0xywja6hquqcl8kcv5sv270vu 
creation_rules:
  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
        - *home-desktop
        - *home-server-1
